name: Rust CI
on:
  push:
  pull_request:

jobs:
  rust:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
      - run: cargo check --all-features --all-targets --workspace --locked
      - run: cargo clippy --all-targets --all-features --workspace --locked